## PYTHON LIBRARIES :- ##

**<span style="color:green"> Python library :-**

Normaly, a library is a collection of books or is a room or place where many books are stored to be used later. Similarly, in the programming world, a library is a collection of codes that can be used later on in a program for some specific well-defined operations. It makes everyday tasks more efficient. It is located in the site-packages folder within the python install directory. Python library has code bundles that can be used again and again in different programs. Library may contain documentation, configuration data, message templates, classes and values etc. For programmers, it makes python programming easier and simpler.

**<span style="color:green">Common libraries are :-**

Some  common libraries for data analysis: like numpy, pandas, scipy are used for data manipulation analysis and scientific computing tasks. Machine learning and Artificial intelligence libraries are: tensor flow, pyTorch, scikit learn and keras. There are over 137,000 python libraries available today. These libraries can be helpful in creating application and models in a variety of fields. For instance, data science, data manipulation, data visulalization, images and many more. 


Example of using python library is :

In [1]:
import statistics
a=([23,45,56,78,54,67])
statistics.mean(a)

53.833333333333336

In this eaxample, in first code, 'import' word is used to enter the library (statistics) in our computer. Then, we create an array assign to 'a' variable and we call the function statistics.mean() that was already occur in the library of statistics. In which we will not use any formulae's to solve the mean only use the library functions.

### <span style="color:red"> NUMPY :- ###

**<span style="color:green">Importance :-**

Numpy stands for Numerical python. Numpy is a python library used for working with arrays. Numpy can be used to perform a wide variety of mathematical operations on array and matrixes.

In python, we have lists that serve the purpose of arrays, but they are slow the process. Numpy aims to provide an array object that is up to 50x faster than traditional python lists. The array dimensional in numpy is called ndarray. It provide a lot of supproting functions that make working ndarray very easy. Array are very frequently used in data science (It is a branch of computer science where we study how to store, use and analyze data for deriving information from it), where speed and resources are very important.

**<span style="color:green">How to import numpy :-**

import numpy as np. We shorten the imported name to np for better readability of code using numpy.

In [2]:
import numpy as np

**<span style="color:green">Examples of numpy for arrays :-**

In [3]:
a=np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In this example, we simply assign the numpy array to 'a' variable, and then disply the array by using simple variable 'a' in 2nd line. It contain one rows and 5 columns. This example represent the syntax of 1 dimensional array.

For 2 dimensional array, we will use this syntax :

In [4]:
a=np.array([[24,50,40,87,8],[30,29,60,80,64],[78,29,19,27,90]])
a

array([[24, 50, 40, 87,  8],
       [30, 29, 60, 80, 64],
       [78, 29, 19, 27, 90]])

This is the example of 2 dimensional array, in which we use 3 arrays by using comma that seperate these 3 arrays, which contain 3 rows and 5 columns. 

**<span style="color:green">Some important points :-**

 1. Rows are horizontal and columns are vertical.
 2. Rows (horizontal dimension) always denoted by 0.
 3. Columns (vertical dimension) always denoted by 1.
 4. One dimensional array always contain one rows and multiple columns eg. [10,15,20,25,30,35,40,45].
 5. Two dimensional array always contain multiple rows and columns eg. [[2,3,6,5,7,8],[10,1,9,11,80,38]].
 6. Cubic is example of 3 dimensional array.
 7. Always remember, For 2 dimensional array, we will use 2 square brackets and for 3 dimensional array, we will use 3 square brackets and so on. 
 8. One dimensional array also known as vector.
 9. Two dimensional array also known as matrix.
 10. Three dimensional or higher than arrays are known as tensor.
 11. Remember that the second name of dimension is axis.
 12. axis=0 shows vertical direction.
 13. axis=1 shows horizontal direction.
     

**<span style="color:green">Checking the datatypes of an array :-**

In [5]:
var=np.array([20,34,17,37,58])
print("Data Type :", var.dtype)

Data Type : int32


In [6]:
d=np.array(["nooram","saira","kafia","laraib","adan"])
print("Data Type :", d.dtype)

Data Type : <U6


In [7]:
m=np.array([2.4,3.4,7.6])
print("Data Type :", m.dtype)

Data Type : float64


These examples shows the data type of an array. In 2nd example <U represent the string datatype.

If we combine the string and integer data values, then, we check the datatype. For example :

In [8]:
var=np.array(["raziya","haniya","daniya",90,80,70])
print("Data Type :", var.dtype)

Data Type : <U11


By using dtype function,we find the datatypes of an array easily. 

**<span style="color:blue">Type Conversion / Type casting :-**

Type conversion is the proces  of converting a data type into another data type. In which, we will use type conversion functions in the program code. This type conversion is also known as Type Casting.

Some instances are :-

In [9]:
var=np.array(["Beleive in yourself"], dtype=bool)
print(var.dtype)

bool


In [10]:
var=np.array([1,2,3,4,5,6,7,8], dtype="f")
print("Data type :", var.dtype)


Data type : float32


In [11]:
var=np.array([2,3,4,5,6,7])
print(var.dtype)
var=np.array([2,3,4,5,6,7], dtype=np.int8)
print(var.dtype)

int32
int8


Firstly, we dis[played simple array datatype, 32 shows the byte of datatype.Then we changed the byte from 32 to 8.

In [12]:
var=np.array([3.4,2.5,45,67,89], dtype=int )
print(var.dtype)
var

int32


array([ 3,  2, 45, 67, 89])

**<span style="color:blue">Basic array functions :-**

In [13]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
np.min(a) # minimum value of an array

1

In [15]:
np.max(a) # maximum value of an array

11

In [16]:
np.argmin(a) # position or indexing of minimum number

0

In [17]:
np.argmax(a) # position or indexing of maximum number

10

In [18]:
np.sqrt(a) # square root of every number

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479])

In [19]:
np.sin(a) # sin value of every number

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
       -0.99999021])

In [20]:
np.cos(a) # cos value of every number

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153,
        0.0044257 ])

In [21]:
np.linspace(1,6,5)

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

The syntax of this function will be : (starting value, ending value, same gap b/w consecutive values/divide values equally)

In [22]:
np.zeros(5) # it returns a new array of given shape and type, where the elements value as 0. Array of zeros with length 5.


array([0., 0., 0., 0., 0.])

In [23]:
np.ones(8) # it returns a new array of given shape and type, where the elements value as 1. Array of ones with length 8.

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.empty(5, dtype=int) # it returns random values and uninitialized entries, with int type.

array([175076204, 538976288, 757935405, 757935405, 538976266])

In [25]:
a=np.array([1,1,1,2,3,1,4]) # avoid to repeate the value and returns unique values
np.unique(a)

array([1, 2, 3, 4])

In [26]:
a=np.array([1,2,3,4,5,6,7,8]) 
np.arange(1,8,2) # syntax (start, stop, steps/gap)

array([1, 3, 5, 7])

In [27]:
a=np.array([4,2,7,6,5,9,1])
np.argsort(a) # it tells that our array is sorted or not and also tell the datatype of array

array([6, 1, 0, 4, 3, 2, 5], dtype=int64)

In [28]:
np.around(a)

array([4, 2, 7, 6, 5, 9, 1])

In [29]:
np.sum(a) # Calculate the sum of elements of numpy array

34

In [30]:
np.std(a) # Calculate the standard deviation of the elements of numpy array.

2.5872528966106905

**<span style="color:blue">Sorting array :-**

Sorting means putting elements in an ordered sequence. Ordered sequence is any sequence like numeric, alphabatic, ascending or descending.

In [31]:
import numpy as np
a=np.array([3,2,0,1])
np.sort(a)

array([0, 1, 2, 3])

In [32]:
b=np.array(["banana","cherry","falsa"])
np.sort(b)

array(['banana', 'cherry', 'falsa'], dtype='<U6')

**<span style="color:blue">Concatination :-**

Concatination function is essentially used to combines numpy arrays together. To join two or more arrays of the same shape along a specified axis. There are several ways to concatenate arrays in numpy. One way is to use the concatenate() function. The concatenate() function takes a list of arrays as input and returns a new array that is the concatenation of the input arrays.

For example, the following code concatenates two arrays :-

**<span style="color:green">1 dimensional array :-**

In [33]:
a=np.array(['d','a','n','i','y','a'])
b=np.array(['s','a','q','i','b'])
np.concatenate((a,b))

array(['d', 'a', 'n', 'i', 'y', 'a', 's', 'a', 'q', 'i', 'b'], dtype='<U1')

**<span style="color:green">2 dimensional array :-**

In [34]:
x=np.array([[1,2,3,4,5],[6,7,8,9,10]])
y=np.array([[11,12,13,14,15],[16,17,18,19,20]])
np.concatenate((x,y))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Another way to concatenate arrays in numpy is to use the + operator. The + operator concatenates two arrays along the first axiss by default. 

For example, the following code concatenates the arrays :-

In [35]:
a=np.array([1,3,6,7])
b=np.array([8,9,0,2])
c=a+b
print(c)

[ 9 12  6  9]


**<span style="color:green">Common functions for concatenation :-**

There are several functions in numpy that can be used to concatenate arrays. The most common ones are :

concatenate() : This is the most general concatenation function. It can concatenate arrays of any dimension and along any axis. We have already seen the example of this function.

stack() : This function concatenate arrays along a new axis. For example :

In [36]:
a=np.array([2,5,6,7])
b=np.array([6,9,0,1])
np.stack((a,b))

array([[2, 5, 6, 7],
       [6, 9, 0, 1]])

hstack() : This function concatenate arrays horizontally, i.e, along the columns, For example :

In [37]:
x=np.array([34,7,8,90,23])
y=np.array([10,2,3,4,5])
np.hstack((x,y))

array([34,  7,  8, 90, 23, 10,  2,  3,  4,  5])

vstack() : This function concatenate arrays vertically, i.e, along the rows. For example : 

In [38]:
np.vstack((x,y))

array([[34,  7,  8, 90, 23],
       [10,  2,  3,  4,  5]])

dstack() : This function concatenate arrays along the depth axis. For example :

In [39]:
np.dstack((a,b))

array([[[2, 6],
        [5, 9],
        [6, 0],
        [7, 1]]])

**<span style="color:green">Check the shape of an array :-**

Using the shape attribute of an array returns tuple of the arrays dimensions. For example, if an array has two dimensions, the shape attribute will return a tuple of length 2. Here is the example of how to use the shape attribute :

In [40]:
h=np.array([1,2,3,4,5])
print((h.shape))

(5,)


It is the tuple of length 1, which means that the array has 1 dimension. Using the ndim attribute of an array returns the number of dimensions of the array. Here is an example of how to use the ndim attribute :

In [41]:
d=np.array([1,3,5,7,9])
print((d.ndim))

1


It means array has 1 dimension. We can also check the size function that returns the total number of elements in the array. Here is an example of how to use the size attribute or function :

In [42]:
l=np.array([2,4,6,8,0])
print((l.size))

5


It shows the total number of elements in the array.

**<span style="color:green">Reshaping the array :-**

Reshaping in numpy is changing the shape of an array without changing its data. The shape of an array is the number of elements in each dimension. By reshaping we can add or remove dimensions or change number of elements in each dimension. We will use the reshape() method.

In [43]:
f=np.array([1,2,3,4,5,6])
f.reshape((2,3)) # syntax (no.of rows, no,of columns)

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
np.reshape(f,newshape=(2,3),order='A') # We can also write the reshape function from this syntax

array([[1, 2, 3],
       [4, 5, 6]])

**<span style="color:blue">Indexing or slicing :-**

Indexing and Slicing are two ways to access elements of a numpy array. Numpy indexing is used for accessing an element from an array by giving it an index value that starts from 0 means that the first element has index 0, and the second has index 1 etc. You can access an array element by referring to its index number. Slicing numpy array means extracting elements from an array in a specific range. Slicing is used to obtain a sequence of element. 

In [45]:
s=np.array([45,67,89,4,56,3,2,56,1])
d=s[3] # it shows that 3 index contain 4 element
print((d))

4


Slicing is specified as a tuple of three numbers : the start index, the stop index, and the step size. The start step is optional and defaults to 0. The stop index is the last element to be included in the slice, and it is not included itself. The step size is optional and defaults to 1.

In [46]:
z=np.array([2,5,6,8,0,3,4,1])
print(z[1: ]) # from 1 index to the ending index

[5 6 8 0 3 4 1]


In [47]:
x=np.array(['n','o','o','r','a','m'])
print(x[2:5]) # from 2 index to 4

['o' 'r' 'a']


In [48]:
b=np.array([4.6,7.0,79,5,7,8,9.7])
print(b[3:6:2])

[5. 8.]


In [49]:
print(z[ :4]) # from starting index to 4 index

[2 5 6 8]


We can also use the negative indices to slice from the end of the array. For example, elements from the third to the first element of the array :

In [50]:
j=np.array([1,2,3,4,5,6,7])
print(j[-3:-1])

[5 6]


In [51]:
k=np.array([1,2,3,4,5])
print(k[::1]) # step size or gap of 1 element

[1 2 3 4 5]


In [52]:
print(k[::-1]) # to alternate the array

[5 4 3 2 1]


**<span style="color:green">Slicing on the basis of concatination :-**

Slicing on the basis of concatenation is done by first concatenating the two arrays, and then slicing the resulting concatenated array. For example, the following code concatenates two arrays, a and b and then slice the resulting concatenated array from index 2 to 5 :

In [62]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=np.concatenate((a,b))
print("After concatenation :", c)
print("Slicing of an array :", c[2:5])               

After concatenation : [ 1  2  3  4  5  6  7  8  9 10]
Slicing of an array : [3 4 5]


Some other things to keep in mind when slicing on the basis of concatenation in numpy :

1. The order of the array in the concatenation matters. In the above example, a was concatenated before b. If the order was reversed, the elements of b would have been printed from index 2 to index 5. For example : 

In [67]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=np.concatenate((b,a))
print(c)
print(c[2:5])

[ 6  7  8  9 10  1  2  3  4  5]
[ 8  9 10]


2. We can also slicing the concatenated array along the multiple axis. For example :-

In [76]:
e=np.array([[1,2,3],[4,5,6]])
r=np.array([[7,8,9],[10,11,12]])
t=np.concatenate((e,r), axis=1)
print(t)
print(t[ :,1:3])

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[2 3]
 [5 6]]


The first line create the array 1. The second line create the array 2. The 3rd line concatenate the array 1 and 2 along the 2nd axis (axis=1). This means that the rows of the arrays will be concatenated together. Then last line prints the elements of t from the 2nd column to the 3rd column. Last line code ([ : , 1:3]) is a slicing operation. The symbol : is used to represent that all rows of the array will be selected. The 1:3 means that the element from index 1 to index 2 will bw selected. In this case, the second and third columns of the concatenated array will be selected. 

In [77]:
b=np.array([1,2,4,5,7,8,3,6,9,10,12,14,16,18,20])
(b[b>7]) # All elements that are greater than 7 will print.

array([ 8,  9, 10, 12, 14, 16, 18, 20])

In [78]:
print(b>10) # it will give us an output in the form of boolean

[False False False False False False False False False False  True  True
  True  True  True]


In [89]:
a=np.array([2,3,4,5,6])
b=np.array([7,8,9,10,11])
c=b[a>1]
c

array([ 7,  8,  9, 10, 11])

**<span style="color:green">Some other operations are :-**

In [79]:
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2=np.array([[11,12,13,14,15],[16,17,18,19,20]])
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

The vstack() function is used to stack array vertically (rows wise). In this example, the vstack() function has stacked the two arrays together to create a new array with 4 rows and 5 columns.

In [80]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

The hstack() function is used to stack array horizontally (column wise). The arrays must all have the same number of rows. If they do not, the hstack() function will raise an error. In this example, hstack() function has stacked the two arrays together to create a new array with 2 rows and 10 columns. 

**<span style="color:blue">Splitting an array :-**

Splitting an array means dividing it into smaller sub-arrays. There are many ways to split an array. Some of the most common methods include :-

Using the split() method, this method divides the array into specified number of sub array of equal size. For example :

In [106]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
d=np.split(a,5) # it splits an array into 5 equal arrays
d

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

Using the hsplit() method, this method divides the array horizontally into sub-array of equal width. For example :-

In [97]:
np.hsplit(a,2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [111]:
x=np.array([1,12,34,2])
x.sum(axis=0)

49

In this example, we add the individual elements of one column to the individual element of another column

**<span style="color:purple">Important quenstion of assignment (what's the difference b/w concatenationa and stack) :-** 

The concatenation and stack functions are both used to combine arrays. The concatenate() function concatenates array along an existing axis. This means that the array must have the same shape along the axis that is being concatenated. For example, if you want to concatenate two 1D arrays they must have the same length. If you want to concatenate two 2D arrays, they must have the same number of rows and columns.For example :

In [114]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

The stack() function concatenates array along a new axis. This means that the array can have different shapes along the axis that is being stacked. For example, you can stack two 1D arrays to create a 2D array, or you can stack two 2D array to create a 3D array. For example : 

In [117]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.stack((a,b)) # this has created 1d to 2d array that contain 2 rows and 3 columns

array([[1, 2, 3],
       [4, 5, 6]])

The concatenate() and stack() functions are both very important tools for combining arrays in numpy. They can be used to simplify data analysis and visualization tasks.